### ISSUE TITLE
We have to add a validation message (warning with comment) at the submission stage if any user added an income statement in Full CH type accounts reports.We have to add a validation message (warning with comment) at the submission stage if any user added an income statement in Full CH type accounts reports.

### ISSUE THREAD

**Issue by Saurabh-ActingOffice** [actingoffice/ActingOffice.App.Dev#1522] opened 2022-05-31 13:42 UTC
We have to add a validation message (warning with comment) at the submission stage if any user added an income statement in Full CH type accounts reports.

**Comment by mukesh-capsitech** [comment] 2022-06-08 14:09
Duplicate of #1521

**Closed by mukesh-capsitech** 2022-06-08 14:09 UTC
Labels: Enhancement, AP
